order:
  pay-timeout-seconds: 60 # 订单支付超时时长，单位：秒。
  create-frequency-seconds: 666 # 订单创建频率，单位：秒

logging:
  level:
    cn.iocoder.springcloud.labx12.userapplication.controller.DemoController: DEBUG

test: true

xx-password: '{cipher}5fca0df4439ee4b2830195555934985442efee67fe1e4bb4cce6fde2ff081a10'
